name: Process master push or pr
on:
  push:
    branches:
      - otp2_opentransport
  pull_request:
    branches:
      - otp2_opentransport
jobs:
  docker-push:
    if: github.ref == 'refs/heads/otp2_opentransport'
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image from master and push it
        run: ./.github/workflows/scripts/build_and_push_dev.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}
